### PR TITLE
🧹 Update to go 1.18

### LINKED ISSUE #243: Prepare for go1.18
Building with a freshly checked out repo, fails to install the controller-gen with golang 1.18.

```
jdiaz@joels-air ~  % go version
go version go1.18 darwin/arm64
jdiaz@joels-air projects  % mkdir test
jdiaz@joels-air projects  % cd test 
jdiaz@joels-air test  % git clone https://github.com/mondoohq/mondoo-operator.git
Cloning into 'mondoo-operator'...
remote: Enumerating objects: 1927, done.
remote: Counting objects: 100% (772/772), done.
remote: Compressing objects: 100% (246/246), done.
remote: Total 1927 (delta 656), reused 526 (delta 526), pack-reused 1155
Receiving objects: 100% (1927/1927), 569.14 KiB | 8.02 MiB/s, done.
Resolving deltas: 100% (1278/1278), done.
jdiaz@joels-air test  % cd mondoo-operator 
jdiaz@joels-air mondoo-operator (main) % make
go: creating new go.mod: module tmp
Downloading sigs.k8s.io/controller-tools/cmd/controller-gen@v0.7.0
go: downloading sigs.k8s.io/controller-tools v0.7.0
go: downloading github.com/spf13/cobra v1.2.1
go: downloading golang.org/x/tools v0.1.5
go: downloading sigs.k8s.io/yaml v1.2.0
go: downloading github.com/fatih/color v1.12.0
go: downloading gopkg.in/yaml.v3 v3.0.0-20210107192922-496545a6307b
go: downloading k8s.io/apiextensions-apiserver v0.22.2
go: downloading k8s.io/apimachinery v0.22.2
go: downloading k8s.io/api v0.22.2
go: downloading github.com/gobuffalo/flect v0.2.3
go: downloading github.com/mattn/go-colorable v0.1.8
go: downloading github.com/mattn/go-isatty v0.0.12
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading github.com/inconshreveable/mousetrap v1.0.0
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/gogo/protobuf v1.3.2
go: downloading k8s.io/utils v0.0.0-20210819203725-bdf08cb9a70a
go: downloading k8s.io/klog/v2 v2.9.0
go: downloading sigs.k8s.io/structured-merge-diff/v4 v4.1.2
go: downloading github.com/google/gofuzz v1.1.0
go: downloading golang.org/x/sys v0.0.0-20210616094352-59db8d763f22
go: downloading gopkg.in/inf.v0 v0.9.1
go: downloading github.com/google/go-cmp v0.5.6
go: downloading github.com/go-logr/logr v0.4.0
go: downloading github.com/json-iterator/go v1.1.11
go: downloading golang.org/x/net v0.0.0-20210520170846-37e1c6afe023
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/modern-go/reflect2 v1.0.1
go: downloading golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1
go: downloading golang.org/x/mod v0.4.2
go: downloading golang.org/x/text v0.3.6
go: added github.com/fatih/color v1.12.0
go: added github.com/go-logr/logr v0.4.0
go: added github.com/gobuffalo/flect v0.2.3
go: added github.com/gogo/protobuf v1.3.2
go: added github.com/google/go-cmp v0.5.6
go: added github.com/google/gofuzz v1.1.0
go: added github.com/inconshreveable/mousetrap v1.0.0
go: added github.com/json-iterator/go v1.1.11
go: added github.com/mattn/go-colorable v0.1.8
go: added github.com/mattn/go-isatty v0.0.12
go: added github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: added github.com/modern-go/reflect2 v1.0.1
go: added github.com/spf13/cobra v1.2.1
go: added github.com/spf13/pflag v1.0.5
go: added golang.org/x/mod v0.4.2
go: added golang.org/x/net v0.0.0-20210520170846-37e1c6afe023
go: added golang.org/x/sys v0.0.0-20210616094352-59db8d763f22
go: added golang.org/x/text v0.3.6
go: added golang.org/x/tools v0.1.5
go: added golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1
go: added gopkg.in/inf.v0 v0.9.1
go: added gopkg.in/yaml.v2 v2.4.0
go: added gopkg.in/yaml.v3 v3.0.0-20210107192922-496545a6307b
go: added k8s.io/api v0.22.2
go: added k8s.io/apiextensions-apiserver v0.22.2
go: added k8s.io/apimachinery v0.22.2
go: added k8s.io/klog/v2 v2.9.0
go: added k8s.io/utils v0.0.0-20210819203725-bdf08cb9a70a
go: added sigs.k8s.io/controller-tools v0.7.0
go: added sigs.k8s.io/structured-merge-diff/v4 v4.1.2
go: added sigs.k8s.io/yaml v1.2.0
/Users/jdiaz/projects/test/mondoo-operator/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
bash: /Users/jdiaz/projects/test/mondoo-operator/bin/controller-gen: No such file or directory
make: *** [generate] Error 127
jdiaz@joels-air mondoo-operator (main) % 
```

Fix this issue and any other others that keep us from building/developing mondoo-operator with go 1.18.

### PR DESCRIPTION
**Pull request by czunker**
Also update tooling:
- controller-gen@v0.9.0
- operator-sdk@1.21.0
- kustomize@v4.5.5

Fixes #243

Signed-off-by: Christian Zunker <christian@mondoo.com>

### CODE REVIEW

**Comment by imilchev** [comment]
one thing that didn't work for me is `mockgen`. It is looking for `mockgen` in my GOBIN path but it is getting installed in `./bin`. What helped was to change the `go:generate` comment to 

```
//go:generate ./../../bin/mockgen -source=./client.go -destination=./mock/client_generated.go -package=mock
```

in `pkg/mondooclient/client.go`

**Comment by czunker** [comment]
Perhaps https://github.com/mondoohq/mondoo-operator/pull/399 helps with this PATH problem too.

**Comment by imilchev** [comment]
I think so because now `mockgen` is installed under `bin/` in this repos workdir. I think if you update the line I mentioned this PR is good to go. Then you can try if it fixes the linux issue as well

**Review by imilchev — APPROVED** [review]

**Comment by czunker** [comment]
@joelddiaz The only open topic is kustomize. We move to this version because of the Mac Silicon issue.

operator-sdk 1.22.0 is also work in progress: https://github.com/mondoohq/mondoo-operator/pull/426

**Pull request merged**
