### PR TITLE
Add basic dependabot config

### PR DESCRIPTION
**Pull request by tas50**
Resolves https://github.com/mondoohq/mondoo-operator/issues/403

Signed-off-by: Tim Smith <tsmith84@gmail.com>

### CODE REVIEW

**Review by joelddiaz — COMMENTED** [review]
Is there a way to dry-run this?

I suspect we'll be inundated with out-of-date packages messages, but a lot of our dependencies are dictated by our dependency on OperatorSDK.

**Comment by czunker** [comment]
That's part of a dry-run:
```
=> updating 20 dependencies: github.com/golang-jwt/jwt/v4, github.com/golang/mock, github.com/jetstack/cert-manager, github.com/onsi/ginkgo/v2, github.com/onsi/gomega, github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring, github.com/spf13/cobra, github.com/stretchr/testify, k8s.io/api, k8s.io/apimachinery, k8s.io/client-go, sigs.k8s.io/controller-runtime, github.com/go-logr/logr, github.com/go-logr/zapr, github.com/google/go-cmp, github.com/google/go-containerregistry, github.com/google/uuid, go.uber.org/zap, k8s.io/utils, sigs.k8s.io/yaml

=== github.com/golang-jwt/jwt/v4 (4.3.0)
 => checking for updates 1/20
 => latest available version is 4.4.2
 => latest allowed version is 4.4.2
 => requirements to unlock: own
 => requirements update strategy: 
 => updating github.com/golang-jwt/jwt/v4 from 4.3.0 to 4.4.2
...
```

We also have different options to ignore dependencies or PR:

https://docs.github.com/en/code-security/dependabot/working-with-dependabot/managing-pull-requests-for-dependency-updates#managing-dependabot-pull-requests-with-comment-commands

https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore

**Comment by joelddiaz** [comment]
> /mock, github.com/jetstack/cert-manager, github.com/onsi/ginkgo/v2, github.com/onsi/gomega, github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring, github.com/spf13/cobra, github.com/stretchr/testify, k8s.io/api, k8s.io/apimachinery, k8s.io/client-go, sigs.k8s.io/controller-runtime, github.com/go-logr/logr, github.com/go-logr/zapr, github.com/google/go-cmp, github.com/google/go-containerregistry, github.com/google/uuid, go.uber.org/zap, k8s.io/utils, sigs.k8s.io

A lot of those k8s.io dependencies are things we inherit from OperatorSDK. It probably makes sense to list them out as exceptions/ignored.

**Comment by joelddiaz** [comment]
> > /mock, github.com/jetstack/cert-manager, github.com/onsi/ginkgo/v2, github.com/onsi/gomega, github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring, github.com/spf13/cobra, github.com/stretchr/testify, k8s.io/api, k8s.io/apimachinery, k8s.io/client-go, sigs.k8s.io/controller-runtime, github.com/go-logr/logr, github.com/go-logr/zapr, github.com/google/go-cmp, github.com/google/go-containerregistry, github.com/google/uuid, go.uber.org/zap, k8s.io/utils, sigs.k8s.io
> 
> A lot of those k8s.io dependencies are things we inherit from OperatorSDK. It probably makes sense to list them out as exceptions/ignored.

Specifically, I'm thinking about k8s.io/api , k8s.io/apimachinery , k8s.io/client-go , sigs.k8s.io/controller-runtime

**Comment by tas50** [comment]
If a dep inherits from another package, it just won't update unless it's in an allowed range. No need to pin those here. The packages themselves will control what versions of the deps are allowed

**Comment by joelddiaz** [comment]
Looks like controller-runtime depends on client-go, api, and apimachinery, so those should be able to be dropped.

That leaves us with controller-runtime as our exception. This makes sense as we change controller-runtime dependencies in lockstep with our OperatorSDK upgrades.

**Review by joelddiaz — APPROVED** [review]

**Pull request merged**
