### PR TITLE
WIP: 🐛 record mondoo-operator image as env var

### PR DESCRIPTION
**Pull request by joelddiaz**
The mondoo-operator is responsible for launching "itself" when running the webhook Pod. The operator needs a way to know which image it has been built for, so store this an the env var MONDOO_OPERATOR_IMAGE.

Use this env var when getting ready to deploy the webhook to set the container image properly.

Signed-off-by: Joel Diaz <joel@mondoo.com>

### CODE REVIEW

**Comment by chris-rock** [comment]
Instead of using an env var, could we compile the git version into the binary? Then it would just pull the default repo image with the specific tag it was built for?

**Comment by joelddiaz** [comment]
> Instead of using an env var, could we compile the git version into the binary? Then it would just pull the default repo image with the specific tag it was built for?

Maybe I'm missing something here...how do do you translate from having the git sha to the version/tag of the container image?

**Comment by chris-rock** [comment]
We would just set go ldflags. 

We get the version from git:
VERSION = git describe --abbrev=0 --tags
v0.0.13
BUILDTAG git rev-list --count HEAD 
108
 
 And then set the build flags via
 
 ```
-ldflags "-s -w -X go.mondoo.com/mondoo.Version=${VERSION} -X go.mondoo.com/mondoo.Build=${BUILDTAG}"
```

Since version is always the latest released tag, it should just work

**Comment by joelddiaz** [comment]
Closing this in favor of the approach in #190

**Pull request closed without merging**
