### PR TITLE
🚀 1.3.2

### PR DESCRIPTION
**Pull request by czunker**
Signed-off-by: Christian Zunker <christian@mondoo.com>

### CODE REVIEW

**Comment by imilchev** [comment]
any reason for the feature bump? From what I was able to see we have only cleanup and test stuff since the previous release

**Comment by czunker** [comment]
> any reason for the feature bump? From what I was able to see we have only cleanup and test stuff since the previous release

The AKS tests have a feature star.

**Comment by imilchev** [comment]
> > any reason for the feature bump? From what I was able to see we have only cleanup and test stuff since the previous release
> 
> The AKS tests have a feature star.

true but they are something we care about, not the end-users

**Comment by czunker** [comment]
> > > any reason for the feature bump? From what I was able to see we have only cleanup and test stuff since the previous release
> > 
> > 
> > The AKS tests have a feature star.
> 
> true but they are something we care about, not the end-users

Agree. Changed to 1.3.2. For the future we should think about, how we could separate internal from user-facing features in the PRs.

**Review by imilchev — APPROVED** [review]

**Pull request merged**
